In [3]:
# from tpot import TPOTClassifier
# from tpot import TPOTRegressor

# tpot_classifier = TPOTClassifier(generations= 5, population_size= 24, offspring_size= 12,
#                                  verbosity= 2, early_stop= 12, n_jobs = -1, use_dask = True, random_state = 42,
#                                  config_dict=
#                                  {
#                                   'sklearn.ensemble.RandomForestClassifier': ranfor_parameters,
#                                   'sklearn.svm.SVC': svc_parameters,
#                                   'xgboost.XGBClassifier': xgb_parameters,
#                                   'sklearn.linear_model.LogisticRegression': logrec_parameters,
#                                   'lightgbm.LGBMClassifier': lgbm_parameters
#                                  }, 
#                                  cv = 4, scoring = 'accuracy')
# tpot_classifier.fit(X_train,y_train)

In [4]:
import pandas as pd
import numpy as np

In [5]:
telescope_data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data',header=None)

In [6]:
telescope_data.head()

,0,1,2,3,4,5,6,7,8,9,10
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g

In [7]:
telescope_data.columns = ['fLength', 'fWidth','fSize','fConc','fConcl','fAsym','fM3Long','fM3Trans','fAlpha','fDist','class']

In [8]:
telescope_data.head()

,fLength,fWidth,fSize,fConc,fConcl,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g

In [9]:
telescope_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19020 entries, 0 to 19019
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   fLength   19020 non-null  float64
 1   fWidth    19020 non-null  float64
 2   fSize     19020 non-null  float64
 3   fConc     19020 non-null  float64
 4   fConcl    19020 non-null  float64
 5   fAsym     19020 non-null  float64
 6   fM3Long   19020 non-null  float64
 7   fM3Trans  19020 non-null  float64
 8   fAlpha    19020 non-null  float64
 9   fDist     19020 non-null  float64
 10  class     19020 non-null  object
dtypes: float64(10), object(1)
memory usage: 1.6+ MB

In [10]:
telescope_data.describe()

,fLength,fWidth,fSize,fConc,fConcl,fAsym,fM3Long,fM3Trans,fAlpha,fDist
count,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000
mean,53.250154,22.180966,2.825017,0.380327,0.214657,-4.331745,10.545545,0.249726,27.645707,193.818026
std,42.364855,18.346056,0.472599,0.182813,0.110511,59.206062,51.000118,20.827439,26.103621,74.731787
min,4.283500,0.000000,1.941300,0.013100,0.000300,-457.916100,-331.780000,-205.894700,0.000000,1.282600
25%,24.336000,11.863800,2.477100,0.235800,0.128475,-20.586550,-12.842775,-10.849375,5.547925,142.492250
50%,37.147700,17.139900,2.739600,0.354150,0.196500,4.013050,15.314100,0.666200,17.679500,191.851450
75%,70.122175,24.739475,3.101600,0.503700,0.285225,24.063700,35.837800,10.946425,45.883550,240.563825
max,334.177000,256.382000,5.323300,0.893000,0.675200,575.240700,238.321000,179.851000,90.000000,495.561000

In [11]:
telescope_data['class'].value_counts()

g    12332
h     6688
Name: class, dtype: int64

In [12]:
telescope_shuffle=telescope_data.iloc[np.random.permutation(len(telescope_data))]
tele=telescope_shuffle.reset_index(drop=True)
tele.head()

,fLength,fWidth,fSize,fConc,fConcl,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,55.5272,12.6516,2.4330,0.4354,0.2528,42.1591,36.7524,-7.9590,13.3310,166.4050,g
1,36.7372,16.5615,2.5871,0.4398,0.2937,27.5738,37.0206,-2.9455,27.5930,190.3500,g
2,42.4594,14.8353,2.6808,0.3191,0.1804,34.6929,29.7121,-15.0021,38.6630,227.9500,h
3,88.5440,16.8029,2.8815,0.2130,0.1382,-23.0108,-74.7420,-9.3482,4.4731,129.6023,h
4,24.8882,7.8008,2.4232,0.6792,0.4472,25.3809,14.8384,-9.8301,38.8998,77.8319,h

In [13]:
tele['class']=tele['class'].map({'g':0,'h':1})

tele.head()

,fLength,fWidth,fSize,fConc,fConcl,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,55.5272,12.6516,2.4330,0.4354,0.2528,42.1591,36.7524,-7.9590,13.3310,166.4050,0
1,36.7372,16.5615,2.5871,0.4398,0.2937,27.5738,37.0206,-2.9455,27.5930,190.3500,0
2,42.4594,14.8353,2.6808,0.3191,0.1804,34.6929,29.7121,-15.0021,38.6630,227.9500,1
3,88.5440,16.8029,2.8815,0.2130,0.1382,-23.0108,-74.7420,-9.3482,4.4731,129.6023,1
4,24.8882,7.8008,2.4232,0.6792,0.4472,25.3809,14.8384,-9.8301,38.8998,77.8319,1

In [14]:
tele_class = tele['class'].values

In [15]:
pd.isnull(tele).any()

fLength     False
fWidth      False
fSize       False
fConc       False
fConcl      False
fAsym       False
fM3Long     False
fM3Trans    False
fAlpha      False
fDist       False
class       False
dtype: bool

In [16]:
tele = tele.fillna(-999)

In [20]:
from sklearn.model_selection import train_test_split
training_indices, validation_indices = training_indices, testing_indices = train_test_split(tele.index,
                                                                                            stratify = tele_class,
                                                                                            train_size=0.75, test_size=0.25)

In [21]:
training_indices.size, validation_indices.size

(14265, 4755)

In [26]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures, RobustScaler

# NOTE: Make sure that the class is labeled 'target' in the data file
tpot_data = pd.read_csv('PATH/TO/DATA/FILE', sep='COLUMN_SEPARATOR', dtype=np.float64)
features = tpot_data.drop('target', axis=1).values
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['target'].values, random_state=42)

# Score on the training set was:0.881597992166
exported_pipeline = make_pipeline(
    PolynomialFeatures(degree=2, include_bias=False, interaction_only=False),
    RobustScaler(),
    GradientBoostingClassifier(learning_rate=0.1, max_depth=6, max_features=0.6, min_samples_leaf=12, min_samples_split=3, n_estimators=100, subsample=0.55)
)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)

C:\ProgramData\Anaconda3\envs\ML\lib\site-packages\ipykernel_launcher.py:9: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':

FileNotFoundError: [Errno 2] No such file or directory: 'PATH/TO/DATA/FILE'

In [25]:
from tpot import TPOTClassifier
from tpot import TPOTRegressor

tpot_classifier = TPOTClassifier(generations= 5, population_size= 24, offspring_size= 12,
                                 verbosity= 2, early_stop= 12, n_jobs = -1, use_dask = True, random_state = 42,
                                 config_dict=
                                 {
#                                   'sklearn.ensemble.RandomForestClassifier': ranfor_parameters,
#                                   'sklearn.svm.SVC': svc_parameters,
#                                   'xgboost.XGBClassifier': xgb_parameters,
#                                   'sklearn.linear_model.LogisticRegression': logrec_parameters,
#                                   'lightgbm.LGBMClassifier': lgbm_parameters
                                 }, 
                                 cv = 4, scoring = 'accuracy')
tpot.fit(tele.drop('class',axis=1).loc[training_indices].values,
         tele.loc[training_indices,'class'].values)

NameError: name 'tpot' is not defined

In [ ]:
# from tpot import TPOTClassifier
# from tpot import TPOTRegressor

# tpot = TPOTClassifier(generations=5,verbosity=2)

# tpot.fit(tele.drop('class',axis=1).loc[training_indices].values,
#          tele.loc[training_indices,'class'].values)